export interface CardCreatorCountry {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: CardCreatorCountry[] = [
  { code: "FR",     name: "France",        flag: "/flags/fr.svg"     },
  { code: "MA",     name: "Morocco",       flag: "/flags/ma.svg"     },
  { code: "US",     name: "United States", flag: "/flags/us.svg"     },
  { code: "CA",     name: "Canada",        flag: "/flags/ca.svg"     },
  { code: "MX",     name: "Mexico",        flag: "/flags/mx.svg"     },
  { code: "BR",     name: "Brazil",        flag: "/flags/br.svg"     },
  { code: "AR",     name: "Argentina",     flag: "/flags/ar.svg"     },
  { code: "GB-ENG", name: "England",       flag: "/flags/gb-eng.svg" },
  { code: "ES",     name: "Spain",         flag: "/flags/es.svg"     },
  { code: "PT",     name: "Portugal",      flag: "/flags/pt.svg"     },
  { code: "DE",     name: "Germany",       flag: "/flags/de.svg"     },
  { code: "IT",     name: "Italy",         flag: "/flags/it.svg"     },
  { code: "NL",     name: "Netherlands",   flag: "/flags/nl.svg"     },
  { code: "BE",     name: "Belgium",       flag: "/flags/be.svg"     },
  { code: "HR",     name: "Croatia",       flag: "/flags/hr.svg"     },
  { code: "JP",     name: "Japan",         flag: "/flags/jp.svg"     },
  { code: "KR",     name: "South Korea",   flag: "/flags/kr.svg"     },
  { code: "AU",     name: "Australia",     flag: "/flags/au.svg"     },
  { code: "SA",     name: "Saudi Arabia",  flag: "/flags/sa.svg"     },
  { code: "EG",     name: "Egypt",         flag: "/flags/eg.svg"     },
  { code: "SN",     name: "Senegal",       flag: "/flags/sn.svg"     },
  { code: "CI",     name: "Ivory Coast",   flag: "/flags/ci.svg"     },
  { code: "GH",     name: "Ghana",         flag: "/flags/gh.svg"     },
  { code: "NG",     name: "Nigeria",       flag: "/flags/ng.svg"     },
  { code: "UY",     name: "Uruguay",       flag: "/flags/uy.svg"     },
  { code: "CO",     name: "Colombia",      flag: "/flags/co.svg"     },
  { code: "CL",     name: "Chile",         flag: "/flags/cl.svg"     },
  { code: "CH",     name: "Switzerland",   flag: "/flags/ch.svg"     },
  { code: "DK",     name: "Denmark",       flag: "/flags/dk.svg"     },
  { code: "SE",     name: "Sweden",        flag: "/flags/se.svg"     },
  { code: "NO",     name: "Norway",        flag: "/flags/no.svg"     },
  { code: "PL",     name: "Poland",        flag: "/flags/pl.svg"     },
  { code: "TR",     name: "Turkey",        flag: "/flags/tr.svg"     },
  { code: "UA",     name: "Ukraine",       flag: "/flags/ua.svg"     },
  { code: "AT",     name: "Austria",       flag: "/flags/at.svg"     },
  { code: "CZ",     name: "Czech Republic",flag: "/flags/cz.svg"     },
  { code: "RS",     name: "Serbia",        flag: "/flags/rs.svg"     },
  { code: "DZ",     name: "Algeria",       flag: "/flags/dz.svg"     },
  { code: "TN",     name: "Tunisia",       flag: "/flags/tn.svg"     },
  { code: "QA",     name: "Qatar",         flag: "/flags/qa.svg"     },
  { code: "AE",     name: "UAE",           flag: "/flags/ae.svg"     },
];
