import type { Team } from "@/types";

export const TEAMS: Team[] = [
  { code: "ARG", name: "Argentina", flag: "🇦🇷" },
  { code: "AUS", name: "Australia", flag: "🇦🇺" },
  { code: "BEL", name: "Belgium", flag: "🇧🇪" },
  { code: "BRA", name: "Brazil", flag: "🇧🇷" },
  { code: "CAN", name: "Canada", flag: "🇨🇦" },
  { code: "CMR", name: "Cameroon", flag: "🇨🇲" },
  { code: "CHL", name: "Chile", flag: "🇨🇱" },
  { code: "COL", name: "Colombia", flag: "🇨🇴" },
  { code: "CRC", name: "Costa Rica", flag: "🇨🇷" },
  { code: "CRO", name: "Croatia", flag: "🇭🇷" },
  { code: "DEN", name: "Denmark", flag: "🇩🇰" },
  { code: "ECU", name: "Ecuador", flag: "🇪🇨" },
  { code: "EGY", name: "Egypt", flag: "🇪🇬" },
  { code: "ENG", name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { code: "FRA", name: "France", flag: "🇫🇷" },
  { code: "GER", name: "Germany", flag: "🇩🇪" },
  { code: "GHA", name: "Ghana", flag: "🇬🇭" },
  { code: "ISL", name: "Iceland", flag: "🇮🇸" },
  { code: "IRN", name: "Iran", flag: "🇮🇷" },
  { code: "ITA", name: "Italy", flag: "🇮🇹" },
  { code: "CIV", name: "Ivory Coast", flag: "🇨🇮" },
  { code: "JAM", name: "Jamaica", flag: "🇯🇲" },
  { code: "JPN", name: "Japan", flag: "🇯🇵" },
  { code: "MEX", name: "Mexico", flag: "🇲🇽" },
  { code: "MAR", name: "Morocco", flag: "🇲🇦" },
  { code: "NED", name: "Netherlands", flag: "🇳🇱" },
  { code: "NZL", name: "New Zealand", flag: "🇳🇿" },
  { code: "NGA", name: "Nigeria", flag: "🇳🇬" },
  { code: "NOR", name: "Norway", flag: "🇳🇴" },
  { code: "PAN", name: "Panama", flag: "🇵🇦" },
  { code: "PAR", name: "Paraguay", flag: "🇵🇾" },
  { code: "PER", name: "Peru", flag: "🇵🇪" },
  { code: "POL", name: "Poland", flag: "🇵🇱" },
  { code: "POR", name: "Portugal", flag: "🇵🇹" },
  { code: "QAT", name: "Qatar", flag: "🇶🇦" },
  { code: "KSA", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "SCO", name: "Scotland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { code: "SEN", name: "Senegal", flag: "🇸🇳" },
  { code: "SRB", name: "Serbia", flag: "🇷🇸" },
  { code: "KOR", name: "South Korea", flag: "🇰🇷" },
  { code: "ESP", name: "Spain", flag: "🇪🇸" },
  { code: "SWE", name: "Sweden", flag: "🇸🇪" },
  { code: "SUI", name: "Switzerland", flag: "🇨🇭" },
  { code: "TUN", name: "Tunisia", flag: "🇹🇳" },
  { code: "TUR", name: "Turkey", flag: "🇹🇷" },
  { code: "URU", name: "Uruguay", flag: "🇺🇾" },
  { code: "USA", name: "United States", flag: "🇺🇸" },
  { code: "WAL", name: "Wales", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
];

export function getTeam(code: string): Team | undefined {
  return TEAMS.find((t) => t.code === code);
}
